package main

import (
	"encoding/json"
	"fmt"
)

type person struct { //we got type Autogenerated []struct from copying from json to go
	First string `json:"First"`
	Last  string `json:"Last"`
	Age   int    `json:"Age"`
}

func main() {
	s := `[{"First":"James","Last":"Bond","Age":32},{"First":"Miss","Last":"Moneypenny","Age":0}]`
	fmt.Printf("%T\n", s)
	bs := []byte(s)
	fmt.Printf("%T\n", bs)

	var people []person //this is a slice of type person
	err := json.Unmarshal(bs, &people)
	if err != nil {
		fmt.Println(err)
	}
	fmt.Println(people)
	for i, v := range people {
		fmt.Println(i)
		fmt.Println(v.First, v.Last, v.Age)
	}
}
